name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build Maven project
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      # Build Docker image to verify Dockerfile works
      - name: Build Docker image
        run: docker build -t todo-app .
